### PR TITLE
bug: update to MUIv5

### LINKED ISSUE #49: bug(mui): Update Material-UI to v5
Bump version of Material-UI library from v4 to v5. 

https://mui.com/material-ui/migration/migration-v4/

### PR DESCRIPTION
**Pull request by Avdieienko**
### Changes
- Upgrade MUI library to v5 as v4 is depreciated

### Related Issue(s)
Closes # 49

### Checklist

```
This section is repository specific. 
If you are seeing this message, the repo is missing a pull request template.
```

### Additional Notes
Upgrade makeStyles function to styled as makeStyles is depreciated

### CODE REVIEW

**Comment by AndreasDemenagas** [comment]
Hi @Avdieienko, if this is complete, let me know and I can review and merge this

**Comment by Avdieienko** [comment]
> Hi @Avdieienko, if this is complete, let me know and I can review and merge this

I thought about it and I think I will also do a migration from makeStyle to styled methods in this branch even though it works for v5 MUI, it is just not supported anymore, give me around week or two.

**Comment by Avdieienko** [comment]
@AndreasDemenagas  Pull request can be reviewed

File: src/app/styles.ts [hunk 1]
```diff
@@ -15,18 +15,20 @@
...
-  viewPaper: {
-    margin: "45px 0px 0px 75px",
-    padding: "15px",
-    boxShadow: "0px 0px 0px 0px",
-  },
-  alert: {
-    marginBottom: "2rem",
-  },
-}));
+// export const useStyles = makeStyles((theme: any) => ({
```
Comment (AndreasDemenagas) [inline src/app/styles.ts]: I would suggest to remove the commented-out lines here. Unless they're needed for some reason I think it's best to keep `main` clean from comments

File: src/pages/dashboard/session/styles.ts [hunk 2]
```diff
@@ -16,190 +16,157 @@
...
+//       marginTop: "1rem",
+//     },
+//     sessionHeadingContainer: {
+//       display: "flex",
+//       marginBottom: "1rem",
+//     },
+//     gridContainer: {
+//       marginBottom: "0.5rem",
+//     }
+//   })
```
Comment (AndreasDemenagas) [inline src/pages/dashboard/session/styles.ts]: Similar to the previous point about the commented-out lines.

**Review by AndreasDemenagas — CHANGES_REQUESTED** [review]

File: src/pages/sessions/styles.ts [hunk 3]
```diff
@@ -15,7 +15,11 @@
     You should have received a copy of the GNU General Public License
     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
-import { makeStyles } from "@material-ui/core";
+
+//!!!!!!!!! TO BE REPLACED WITH styled() WHEN DOING "feat: style session table in /sessions #94" GITHUB ERROR
+// (look for other styles.ts files as an example)
```
Comment (AndreasDemenagas) [inline src/pages/sessions/styles.ts:23]: I'm not entirely sure what you mean here with the GithHub error.

Comment (Avdieienko) [reply src/pages/sessions/styles.ts:23]: Because this page( /sessions ) right now does not use its own styling (uses dashboard/session styling) and github issue #94 suggest to change it so that it will use its own styling. Thus, currently this file is not in use and I didnt change anything there. If needed I can change those stylings to v5 styled.

Comment (AndreasDemenagas) [reply src/pages/sessions/styles.ts:23]: Oh I see. Thanks for that.

Comment (Avdieienko) [reply src/pages/sessions/styles.ts:23]: I will write about that more detailed in comments there just in case

**Comment by Avdieienko** [comment]
@AndreasDemenagas did what you asked.

**Review by AndreasDemenagas — APPROVED** [review]
